html, body {
  margin: 0;
  padding: 0;
  background: #f3f4f6;
  color: #111827;
  font-family: Arial, sans-serif;
}

* { box-sizing: border-box; }

button, input {
  font: inherit;
}

a {
  color: inherit;
}
