import express from 'express';
import { randomUUID } from 'node:crypto';
import { query } from '../config/database.js';
import { connectSession, status, disconnect } from '../services/whatsapp.service.js';
const router = express.Router();
router.post('/create', async (req, res, next) => { try { const id = randomUUID(); const name = req.body.name || 'Test session'; await query('INSERT INTO sessions (id, session_name, status) VALUES ($1,$2,$3)', [id, name, 'connecting']); await connectSession(id); res.status(201).json({ session: { id, name } }); } catch (e) { next(e); } });
router.get('/:id/status', (req, res) => res.json(status(req.params.id)));
router.get('/:id/qr', (req, res) => res.json(status(req.params.id)));
router.post('/:id/disconnect', async (req, res, next) => { try { await disconnect(req.params.id); await query('UPDATE sessions SET status=$1 WHERE id=$2', ['disconnected', req.params.id]); res.json({ ok: true }); } catch (e) { next(e); } });
export default router;
